pipeline {
  agent none
  stages {
   stage('Build Docker Image') {
      agent any
      steps {
        script {
          // Print the current directory
                    sh 'pwd'
          
          // Build the Docker image
          def appImage = docker.build("web-app", "-f 'Multi-Agent-Deploy\\ pipeline/Multi-Stage pipeline/Dockerfile' .")

          // Run the Docker container, exposing port 80
          appImage.run("-p 80:90 --name my-webapp-container")
        }
      }
    }
  }
}
